### ISSUE TITLE
Getting compile error

### ISSUE THREAD

**Issue by fazpu** [NetanelBasal/ngx-text-equality-validator#1]
Hi, thank you for the library!

I am getting error:
`ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in app/client/node_modules/ngx-text-equality-validator/node_modules/@angular/core/core.d.ts, resolving symbol TextEqualityValidatorModule in app/client/node_modules/ngx-text-equality-validator/dist/ngx-text-equality-validator.module.d.ts, resolving symbol TextEqualityValidatorModule in app/client/node_modules/ngx-text-equality-validator/dist/ngx-text-equality-validator.module.d.ts
`

I believe it is AOT related.

**Comment by NetanelBasal** [comment]
Hey, can you create a plunker that will recreate the problem? For everyone including me, it works with AOT.

**Comment by fazpu** [comment]
I am sorry for the late comment. I was not able to reproduce the problem again. It is working. The issue can be closed.
